http:
  address: localhost:8080
  metrics:
    enable: true
    #token: aaaaaaaa
  session:
    enable: true
    # store:
    #   type: redis
    container:
      ## secretbox is default
      type: jwt
      # secretbox:
      #   key: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      jwt:
        algorithm: hs256
        key: aaaaaaaa
    # validator:
    #   refresh: 5s
  proxy:
    enable: true
    upstreams:
      default: "http://127.0.0.1:8082"
  csrf:
    enable: true
    container:
      secretbox:
        key: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

proxy:
  prefix: "/auth"
  user:
    retpath:
      rules:
        - type: "regexp"
          expr: "^/.+$"
    profile:
      rules:
        - type: "regexp"
          key: "mail"
          expr: "^[^@]+@corpix\\.ru$"
      headers:
        enable: false
        map:
          # NOTE: empty value removes header from headers list
          connector: ""
          display-name: ""
          avatar-url: ""

  connectors:
    enable: ["basic", "oauth"]
    # slack:
    #   oauth:
    #     client-id: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    #     client-key: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    #     redirect-url: "https://localhost/goetia/connector/slack/callback"
    # oidc:
    #   label: "keycloak"
    #   oauth:
    #     auth-url: "https://keycloak/auth/realms/master/protocol/openid-connect/auth"
    #     token-url: "https://keycloak/auth/realms/master/protocol/openid-connect/token"
    #     client-id: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    #     client-key: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    #     redirect-url: "https://localhost/goetia/connector/oidc/callback"
    #   user-mappings:
    #     email: "mail"
    #     groups: "groups"
    #     name: "displayName"
    #     preferred_username: "name"
    #   user-url: "https://keycloak/auth/realms/master/protocol/openid-connect/userinfo"
    basic:
      users:
        corpix:
          password: "qwerty"
          # password-file: ...
          mail: "me@corpix.ru"
          groups: ["admin", "owner"]
          display-name: "Dmitry Moskowski"
          avatar-url: "https://avatars.githubusercontent.com/u/747362"

    oauth:
      authorize-url: http://auth.pluto.backbone/providers/oidc/authorize
      token-url: http://auth.pluto.backbone/providers/oidc/token
      redirect-url: http://127.0.0.1:8080/auth/connectors/oauth/callback
      profile-url: http://auth.pluto.backbone/providers/oidc/profile
      client-id: test
      state-token:
        container:
          secretbox:
            key: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

    telegram:
      groups: [-647425492]
      bot-token: "5659812166:AAHTsJIg-1ie3rzI8u7LvuicakkpmczTCgY"
      token:
        container:
          secretbox:
            key: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

  providers:
    enable:
      #- oauth
      - oidc
    oauth:
      tokens:
        code:
          container:
            type: jwt
            jwt:
              algorithm: hs512
              key: aaaaaaaa
        access:
          container:
            type: jwt
            jwt:
              algorithm: hs512
              key: bbbbbbbb
        refresh:
          container:
            type: jwt
            jwt:
              algorithm: hs512
              key: cccccccc
      applications:
        app:
          label: "test app"
          key: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
          redirect-uri: "http://127.0.0.1:3000/login/generic_oauth"
          profile:
            map:
              connector: ""
              avatar-url: "image"
      paths:
        profile: /userinfo
    oidc:
      tokens:
        code:
          container:
            type: jwt
            jwt:
              algorithm: es512
              key: |
                -----BEGIN EC PRIVATE KEY-----
                MIHcAgEBBEIB9hjt4SMz8Miwflpq3i+HqRD6DFG0NcBm4+TbleDWMW6eiNXHBU0U
                XQa1l3kJX4CqH78JzuJzpUeKnpigUgbvY6mgBwYFK4EEACOhgYkDgYYABABAhfxS
                q4IUhLztU3M5Yo+NdwqMDPnNMWm2LpgNdeJjpK/WKwbMH4x0Uxqwcp/VkwIHgrge
                rzOoGaRBy3x8v/2ecQHegB0RfGWX0Wjnz3Hjew/qC4XXiJCZj0TrxQyLq4avy+2r
                AU3XosZTvMTIn1IgRp7ARp+nDkKDRKdD/dvRvXiWsw==
                -----END EC PRIVATE KEY-----
        access:
          container:
            type: jwt
            jwt:
              algorithm: es512
              key: |
                -----BEGIN EC PRIVATE KEY-----
                MIHcAgEBBEIAV8ot2bQMeEv5/lkpfZKLKAajasFOgHYurbPmzzhV76+eL7CjAtRW
                uYbX/Mf1QybMSuRxpybbVmXNGF+ePmoPdZSgBwYFK4EEACOhgYkDgYYABAGPQ8Kh
                iH+jjYCOfVnk9UnwuyMGm03EAWHAlU1bLx/Nl7gujwK8OUrlfgAK+9EfUbvQvJ5v
                Sp934k+N7YAAmQAi3gAD1sHz0xJr4vElrAmtC4zN/Zx007jl4zFH9Aapc+bM0BRt
                E/d9CPR79+ktpLvdIppDTY9X5nn03WoNkuwXW/x3VA==
                -----END EC PRIVATE KEY-----
        refresh:
          container:
            type: jwt
            jwt:
              algorithm: es512
              key: |
                -----BEGIN EC PRIVATE KEY-----
                MIHcAgEBBEIB9w09n7rLGxf//w+rNLYKypuz7HRvjljW9xqCaMbGEqFArtK2hVI6
                54NV48g4VI02gSoXPNRfCg9OLBKC1eK3VkOgBwYFK4EEACOhgYkDgYYABAA31dHg
                EQDO0YX/BiH8byCfu8vbaRyvxgK/0jkziwkgJ7iyf0W+/cBotSeMAzrCiGvm2Z0f
                /n+8vfRa6VEn3rNbqgF5CWUR/m3/3VFVGCo3MrZ0LyzEbZgK9o53hhALieHVZK80
                8TmQj6d+5pHHZqzJimvWY5pbjoe6Q6UUwJ4SM7Y0qw==
                -----END EC PRIVATE KEY-----
        id:
          container:
            type: jwt
            jwt:
              algorithm: es512
              key: |
                -----BEGIN EC PRIVATE KEY-----
                MIHcAgEBBEIAjD0gUsn1sMDbx6/V6mrDJIsYz349emY9Ctp0+1AGDgWPwABnUnyp
                mMnPkbUl7RN64Ugac8IWxHo81Dy8urz73Q6gBwYFK4EEACOhgYkDgYYABAEQIvcR
                ksZsMupNV7xAdrkm1Ru8pgw7xMXOG0V7Hbx8Onp9lS6M0pn6IPZEsjN5L5VkuVMH
                P53rsL4voNaev3lXlwA/YqPZBOHQes1D/pxZrTWKVcnErld5taZYgzYXZB0Hvp/v
                qUhfnU1umoduSXjm6qkYS3GF86i/4Y4N5JCYZsgv9w==
                -----END EC PRIVATE KEY-----
      applications:
        app:
          label: "test app"
          key: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
          # grafana
          # redirect-uri: "http://127.0.0.1:3000/login/generic_oauth"
          # gitea
          redirect-uri: "http://127.0.0.1:3000/user/oauth2/goetia/callback"
          profile:
            map:
              connector: ""
              avatar-url: "image"
              display-name: "name"
              mail: "email"
              name: "login"
      paths:
        discovery: /discover
